import Head from 'next/head'
import Link from 'next/link'
import { blogPosts } from '../lib/data'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="space-y-4">
        {blogPosts.map((post) => (
          <BlogPostList key={post.slug} {...post} />
        ))}
      </div>



    </div>
  )
}

function BlogPostList({ slug, title, date, content }) {
  return (
    <div className="border-green-800 border-2 rounded-lg shadow p-4">
      <div><Link href={`/blog/${slug}`}>
        <a className="font-bold">{title}</a>
      </Link>
      </div>
      <div>{date}</div>
      <div>{content}</div>
    </div>
  )
}
